# -*- coding: utf-8 -*-
"""WHO New

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ghZcMJ9Uhkh4-3HwNEg0l-yI6RixPwIK

# Importações:
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
import seaborn as sns
import geopandas as gpd
import folium
import json
import requests
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

"""Tradução: Estamos "abrindo nossa caixa de ferramentas" - cada biblioteca tem uma função específica:

pandas: Nosso organizador de dados (como uma planilha inteligente)

matplotlib e seaborn: Ferramentas para criar gráficos bonitos

plotly: Para gráficos interativos que podemos clicar e explorar

numpy: Calculadora avançada para números
"""

df = pd.read_csv('/content/drive/MyDrive/meusprojetoscolab/who_suicide_statistics.csv')

"""O que acontece: Estamos importando a base de dados da OMS que contém informações sobre suicídios por país, ano, idade e gênero.

# Correção de nomes
"""

correcao_nomes = {
    'Brunei Darussalam': 'Brunei',
    'Cabo Verde': 'Cape Verde',
    'Czech Republic': 'Czechia',
    'Falkland Islands (Malvinas)': 'Falkland Islands',
    'Hong Kong SAR': 'Hong Kong',
    'Iran (Islamic Rep of)': 'Iran',
    'Russian Federation': 'Russia',
    'Republic of Korea': 'South Korea',
    'Republic of Moldova': 'Moldova',
    'Syrian Arab Republic': 'Syria',
    'TFYR Macedonia': 'North Macedonia',
    'United States of America': 'United States',
    'Venezuela (Bolivarian Republic of)': 'Venezuela',
    'Virgin Islands (USA)': 'United States Virgin Islands',
    'Occupied Palestinian Territory': 'Palestine'
}

df['country_corrigido'] = df['country'].replace(correcao_nomes)

"""Por que isso é importante: Alguns países têm nomes muito longos ou oficiais, então simplificamos para que apareçam melhor nos mapas e gráficos.

# Visão Geral dos Dados:

Dados no geral
"""

df.head()

df.tail()

df.describe()

"""Resultados interessantes que encontramos:

- Dados de 1979 a 2016 - Uma análise de 37 anos!

- 101 países representados

- Mais de 4 milhões de registros para analisar

Quantidade de países representados
"""

totalcountries = df['country'].unique().size
totalcountries

"""Período coberto (anos mínimo e máximo)"""

years = df['year'].unique()
minyear = years.min()
maxyear = years.max()
print(minyear, maxyear)

"""Colunas e tipos de dados"""

df.dtypes

"""# Qualidade dos dados:"""

allnullcounts = df.isnull().sum()
print(allnullcounts)

percentage = df.isnull().mean() * 100
print(percentage.round(2).astype(str) + '%')

"""Descoberta: Encontramos alguns dados faltantes (cerca de 7%), o que é normal em bases históricas tão grandes. Isso não compromete nossa análise.

# Análise Exploratória Inicial:

Países que têm as maiores taxas de suicídio
"""

top = df.groupby('country')['suicides_no'].sum().sort_values(ascending=False).head(10).astype(int)
top

"""Países que têm as menores taxas de suicídio"""

top = df.groupby('country')['suicides_no'].sum().sort_values(ascending=True).head(10).astype(int)
top

"""O que isso faz: Agrupa todos os dados por país e soma o total de suicídios, mostrando os 10 países com números mais altos.

Taxa de suicídio entre os 2 sexos
"""

sex = df.groupby('sex')['suicides_no'].sum().astype(int)
sex

"""Descoberta importante: Encontramos uma diferença significativa entre homens e mulheres.

Taxa de suicídio entre as idades
"""

sex = df.groupby('age')['suicides_no'].sum().astype(int)
sex

"""Padrão encontrado: As faixas etárias de 35-54 anos e 55-74 anos mostram números mais altos.

# Visualização de Dados
"""

plt.figure(figsize=(10, 6))
df_grouped = df.groupby('sex')['suicides_no'].sum()
bars = plt.bar(df_grouped.index, df_grouped.values, color=['pink', 'lightblue'])
for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2., height,
             f'{height:,.0f}',
             ha='center', va='bottom')

plt.xlabel('Sexo', fontsize=12)
plt.ylabel('Número Total de Suicídios', fontsize=12)
plt.title('Número Total de Suicídios por Gênero (Em milhões)', fontsize=14, fontweight='bold')
plt.grid(axis='y', alpha=0.3)
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

"""Insight: Os números são significativamente maiores entre homens."""

age_order = ['5-14 years', '15-24 years', '25-34 years', '35-54 years', '55-74 years', '75+ years']
df['age'] = pd.Categorical(df['age'], categories=age_order, ordered=True)

df_grouped = df.groupby('age', as_index=False)['suicides_no'].sum()

fig, ax = plt.subplots(figsize=(12, 6))
bars = ax.bar(df_grouped['age'], df_grouped['suicides_no'], color=['red', 'orange', 'yellow', 'green', 'blue', 'purple'])

ax.set_xlabel('Idade')
ax.set_ylabel('Taxa de Suicídio')
ax.set_title('Taxa de Suicídio por Idade (Em milhões)', fontsize=14, fontweight='bold')

for bar in bars:
    height = bar.get_height()
    if not np.isnan(height):
        ax.text(bar.get_x() + bar.get_width() / 2, height, f'{height:,.0f}', ha='center', va='bottom')

plt.grid(axis='y', alpha=0.3)
plt.show()

"""Padrão: Pessoas na meia-idade mostram os números mais altos."""

df_grouped = df.groupby('country', as_index=False)['suicides_no'].sum()
df_top10 = df_grouped.sort_values(by='suicides_no', ascending=False).head(10)
df_top10['country'] = pd.Categorical(df_top10['country'], categories=df_top10['country'], ordered=True)
fig, ax = plt.subplots(figsize=(12, 6))
bars = ax.bar(df_top10['country'], df_top10['suicides_no'], color=plt.cm.tab10.colors)

for bar in bars:
    height = bar.get_height()
    if not np.isnan(height):
        ax.text(bar.get_x() + bar.get_width() / 2, height, f'{height:,.0f}', ha='center', va='bottom')

ax.set_xlabel('País')
ax.set_ylabel('Número de Suicídios')
ax.set_title('Top 10 Países com Maior Número de Suicídios (Em milhões)', fontsize=14, fontweight='bold')
plt.grid(axis='y', alpha=0.3)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

df_grouped = df.groupby(['age', 'sex'], as_index=False)['suicides_no'].sum()

plt.figure(figsize=(10, 6))
ax = sns.barplot(
    data=df_grouped,
    x='age',
    y='suicides_no',
    hue='sex',
    palette={'male': 'lightblue', 'female': 'pink'}
)

plt.xlabel('Idade', fontsize=12)
plt.ylabel('Número de Suicídios', fontsize=12)
plt.title('Número de Suicídios por Idade e Gênero', fontsize=14, fontweight='bold')

plt.title('Número de Suicídios por Faixa Etária e Gênero (Em milhões)', fontweight='bold')
plt.xlabel('Faixa Etária')
plt.ylabel('Número de Suicídios')
plt.xticks(rotation=45)
plt.tight_layout()

for p in ax.patches:
    height = p.get_height()
    if height > 0:
        ax.annotate(f'{int(height):,}',
                    (p.get_x() + p.get_width() / 2, height),
                    ha='center', va='bottom', fontsize=9)

plt.show()

df_grouped = df.groupby('year', as_index=False)['suicides_no'].sum()
df_grouped['suicides_million'] = df_grouped['suicides_no']

fig = px.line(df_grouped, x='year', y='suicides_million', markers=True,
              title='Número Total de Suicídios por Ano',
              labels={'year': 'Ano', 'suicides_million': 'Número de Suicídios'},
              hover_data={'year': True, 'suicides_million': ':.f'})

fig.show()

"""Tendência: Como os números mudaram ano após ano."""

df_agg = df.groupby('country_corrigido').agg({'suicides_no': 'sum', 'population': 'sum'}).reset_index()
df_agg['taxa_suicidio'] = (df_agg['suicides_no'] / df_agg['population']) * 100000
top10 = df_agg.sort_values('suicides_no', ascending=False).head(10)

plt.figure(figsize=(12, 6))
bars = plt.bar(top10['country_corrigido'], top10['taxa_suicidio'], color='teal')
plt.xlabel('País')
plt.ylabel('Taxa de Suicídio por 100 mil habitantes')
plt.title('Taxa de Suicídio por País (Top 10 em total de suicídios, todos os anos)', fontweight='bold')
plt.xticks(rotation=45)
plt.tight_layout()

for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, height, f'{height:.2f}', ha='center', va='bottom', fontsize=10)

plt.show()

df_geo = df.groupby('country_corrigido').agg({
    'suicides_no': 'sum'
}).reset_index()

df_geo['suicides_no_fmt'] = df_geo['suicides_no'].apply(lambda x: f'{int(x):,}'.replace(',', '.'))

custom_colors = ['#ffffff', '#fff176', '#ff9800', '#e53935', '#4e342e']

fig = px.choropleth(
    df_geo,
    locations='country_corrigido',
    locationmode='country names',
    color='suicides_no',
    hover_name='country_corrigido',
    hover_data={'suicides_no': False, 'suicides_no_fmt': True},
    color_continuous_scale=custom_colors,
    title='Total de Suicídios por País (Todos os Anos)',
    labels={'suicides_no': 'Total de Suicídios'}
)

fig.update_geos(
    showcoastlines=True, coastlinecolor="Gray",
    showland=True, landcolor="WhiteSmoke",
    showocean=True, oceancolor="LightBlue",
    projection_type="natural earth"
)

fig.update_layout(
    title_font_size=22,
    font=dict(family="Arial", size=12),
    coloraxis_colorbar=dict(title='Total de Suicídios'),
    margin={"r":0,"t":60,"l":0,"b":0}
)

fig.show()

"""Funcionalidade: Um mapa colorido onde você pode passar o mouse sobre cada país e ver os números exatos."""

df_geo = df.groupby('country_corrigido').agg({'suicides_no': 'sum', 'population': 'sum'}).reset_index()
df_geo['taxa'] = (df_geo['suicides_no'] / df_geo['population']) * 100000
df_geo['taxa_fmt'] = df_geo['taxa'].apply(lambda x: f'{x:,.2f}'.replace(',', 'X').replace('.', ',').replace('X', '.'))

fig = px.choropleth(
    df_geo,
    locations='country_corrigido',
    locationmode='country names',
    color='taxa',
    hover_name='country_corrigido',
    hover_data={'taxa': False, 'taxa_fmt': True},
    color_continuous_scale=['#ffffff', '#fff176', '#ff9800', '#e53935', '#4e342e'],
    title='Taxa de Suicídio por País (por 100 mil habitantes)'
)
fig.update_geos(showcoastlines=True, landcolor="WhiteSmoke", oceancolor="LightBlue", projection_type="natural earth")
fig.update_layout(margin={"r":0,"t":60,"l":0,"b":0})
fig.show()

df_sex_year = df.groupby(['year', 'sex'])[['suicides_no', 'population']].sum().reset_index()
df_sex_year['taxa'] = (df_sex_year['suicides_no'] / df_sex_year['population']) * 100000

plt.figure(figsize=(12, 6))
sns.lineplot(data=df_sex_year, x='year', y='taxa', hue='sex', palette='Set1')
plt.title('Evolução da Taxa de Suicídio por Sexo (por 100 mil)', fontweight='bold')
plt.xlabel('Ano')
plt.ylabel('Taxa por 100 mil')
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

df_clust = df.groupby('country_corrigido')[['suicides_no', 'population']].sum().reset_index()

X = StandardScaler().fit_transform(df_clust[['suicides_no', 'population']])

df_clust['cluster'] = KMeans(n_clusters=3, random_state=42).fit_predict(X)

plt.figure(figsize=(14, 8))

cores = ['#2E8B57', '#FFA500', '#1E90FF']
nomes_grupos = ['Grupo 1 - Moderado', 'Grupo 2 - Populoso', 'Grupo 3 - Pequeno']

for cluster_num in range(3):
    dados_grupo = df_clust[df_clust['cluster'] == cluster_num]
    plt.scatter(dados_grupo['suicides_no'], dados_grupo['population'],
               c=cores[cluster_num], label=nomes_grupos[cluster_num], s=80, alpha=0.7)

paises_destacar = ['Russia', 'United States', 'Japan', 'France', 'Germany',
                  'Ukraine', 'Brazil', 'South Korea', 'Poland', 'United Kingdom']

for i in range(len(df_clust)):
    pais = df_clust['country_corrigido'].iloc[i]
    if pais in paises_destacar:
        suicidios_formatado = f"{int(df_clust['suicides_no'].iloc[i]):,}"
        plt.annotate(f"{pais}\n({suicidios_formatado})",
                    (df_clust['suicides_no'].iloc[i], df_clust['population'].iloc[i]),
                    xytext=(8, 8), textcoords='offset points',
                    fontsize=9, alpha=0.8,
                    bbox=dict(boxstyle="round,pad=0.2", facecolor="white", alpha=0.7))

plt.title('Análise de Grupos: Países por Padrões de Suicídio e População',
          fontsize=15, fontweight='bold', pad=15)
plt.xlabel('Total de Suicídios Registrados', fontsize=12)
plt.ylabel('População Total do País', fontsize=12)

plt.legend(title='Grupos de Países', title_fontsize=11,
           loc='upper right', frameon=True, fancybox=True)

plt.grid(True, alpha=0.2)
plt.tight_layout()
plt.show()

"""ANÁLISE DE GRUPOS DE PAÍSES

Esta análise agrupa os países em três categorias baseadas em seu tamanho populacional e números totais de suicídio registrados:

GRUPO 1 - MODERADO (Verde):
Países com números moderados tanto em população quanto em suicídios. São nações que geralmente estão em desenvolvimento ou têm tamanho médio.

GRUPO 2 - POPULOSO (Amarelo):
Países com grande população total. Estes países naturalmente tendem a ter números absolutos mais altos de suicídio simplesmente por terem mais habitantes.

GRUPO 3 - PEQUENO (Azul):
Países com população reduzida. Os números totais de suicídio são menores, mas isso não necessariamente indica melhores condições - a taxa por habitante pode ser mais reveladora.

Os números entre parênteses representam o total de suicídios registrados em cada país durante todo o período analisado.

Esta divisão em grupos ajuda a identificar padrões e fazer comparações mais significativas entre países com características similares.

# Insights

**Principais descobertas**

1. Disparidade de Gênero Significativa

Os homens representam aproximadamente 3/4 de todos os casos registrados

Necessidade urgente de políticas de saúde mental voltadas para a população masculina

2. Distribuição por Faixa Etária Reveladora

Faixas de 35-54 anos e 55-74 anos concentram os maiores números

Pessoas em idade economicamente ativa são as mais afetadas

Idosos também apresentam números preocupantes

3. Tendência Temporal Preocupante

Apesar de flutuações anuais, os números permanecem elevados ao longo das décadas

Indicativo de que as estratégias atuais precisam ser reavaliadas

4. Distribuição Geográfica Heterogênea

Países do Leste Europeu e da antiga União Soviética aparecem com frequência entre os mais afetados

Fatores históricos, econômicos e culturais influenciam fortemente os padrões

5. Análise de Grupos Estratégica

Países populosos naturalmente têm números absolutos maiores

A taxa por 100 mil habitantes é um indicador mais justo para comparações

Países em desenvolvimento enfrentam desafios específicos

**Recomendações Baseadas em Dados**

Para Políticas Públicas:

Desenvolver programas específicos por gênero e faixa etária

Fortalecer sistemas de prevenção em países com taxas historicamente altas

Implementar campanhas de conscientização focadas em grupos vulneráveis

Para Pesquisas Futuras:

Investigar os fatores culturais e socioeconômicos por trás das disparidades regionais

Estudar a eficácia de diferentes abordagens de prevenção por tipo de população

Analisar a correlação entre crises econômicas e taxas de suicídio

Para Ação Imediata:

Capacitar profissionais de saúde para identificação precoce de riscos

Expandir serviços de apoio psicológico gratuito

Criar redes de apoio comunitárias

**Limitações e Considerações**

Dados históricos podem não refletir a realidade atual

Subnotificação é um problema comum em estatísticas de saúde mental

Fatores culturais influenciam a forma como diferentes sociedades relatam e lidam com o tema

**Conclusão Final**

Esta análise revela padrões consistentes que transcendem fronteiras nacionais, destacando a necessidade de uma abordagem global coordenada para a prevenção do suicídio. Os dados nos mostram que, embora existam particularidades regionais, o sofrimento mental é um desafio universal que demanda respostas baseadas em evidências, empatia e ação concertada.

Os números contam uma história - cabe a nós escrever os próximos capítulos com políticas eficazes e compaixão.
"""